version: 2.1

jobs:
  build-and-test:
    working_directory: ~/Anythink-Market-cc4ax/frontend
    docker:
      - image: cimg/node:16.18
    steps:
      - checkout:
          path: ~/Anythink-Market-cc4ax
      - run:
          name: Install deps
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test